export const IGNORED_NAMES: [string, boolean][] = [
  ['App', true],
  ['Home', true],
  ['item', true],
  ['Login', false],
  ['Sign In', false],
  ['Sign Up', false],
  ['loading...', false],
  ['Loading…', false],
];

export const IGNORED_APPS: [string, boolean][] = [
  ...IGNORED_NAMES,
  ['React App', true],
  ['Home Assistant', true],
  ['Create React App', true],
  ['Plesk Obsidian', false],
  ['3CX Webclient', true],
  ['Jitsi Meet', true],
  ['Nextcloud', true],
  ['UISP', true],
];

export const IGNORED_DOMAINS: string[] = [
  'vultrusercontent.com',
  'linodeusercontent.com',
  'googleusercontent.com',
  'positive-dedicated.net',
  'comcast.net',
  'duckdns.org',
  'linode.com',
  'your-server.de',
  'cloudsouth.com',
  'cloudfront.net',
  'plesk.page',
  'wpengine.com',
  'weebly.com',
  'spectrum.com',
  'pleaseignore.com',
  'hostwindsdns.com',
  'secureserver.net',
  'amazonaws.com',
  'awsglobalaccelerator.com',
  'awsglobalaccelerator.com',
  'akamaitechnologies.com',
  'mentorcliq.com',
  'cribl-staging.cloud',
  'cribl.cloud',
  'ford.com',
  'ibm.com',
  'spectrum.com',
  'v2cloud.com',
  'newsdirect.com',
  'datamasonscloud.com',
  'contaboserver.net',
  'appfolio.com',
];

export const SEPARATORS = [
  '|',
  '｜',
  '-',
  '-',
  '-',
  '–',
  ':',
  '=',
  '~',
  '•',
  '#',
  '*',
  '/',
  '»',
  '🚀',
  '❤️‍🔥',
  '🎖️',
  '  ',
  '  ',
  '\n',
  '\r',
  '\r\n',
];
